# config.yaml
defaults:
  - _self_

env: null
model_name: null
model_type: null
down_sample_ratio: null
language_only: null
eval_sets: null
chat_history: null
n_shots: null
multiview: null
detection_box: null
multistep: null
resolution: null
exp_name: null
visual_icl: null
tp: null
easyr1_format: null
prompt_template_path: null
point_input_resolution: null
point_output_resolution: null
env_feedback: null
memory_compression: null
segment_len: null
log_level: null
max_episode_steps: null
max_invalid_actions: null
topdown_camera_y_offset: null
topdown_min_height: null
topdown_max_height: null
